### ISSUE TITLE
Google popping up all the time is annoying, here's my solution

### ISSUE THREAD

**Issue by Bergenfrundt** [cherche/fuchsia#11]
Make it so Fuchsia says "I'm sorry, i didn't quite understand that. Would you like me to Google it instead?"

And you can add an else if y.startswith Google/Search for... then it goes straight to Google.

**Comment by cherche** [comment]
Another solution could be to embed the Google search page.

The problem is that after "Would you like me to Google it instead?", the natural response is "yes", and that means that the search query needs to be saved which isn't possible with the local scope the variables have inside the function.

Edit: I should be able to use http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q= to get the results and put them in a box like the movie box.

Edit 2: So that didn't work. I'll probably just leave it as it is for now. Changing anything would be quite difficult.

**Comment by cherche** [comment]
I found that the Bing Search API _should_ work. In fact, Siri uses it. http://www.bing.com/dev/
